#+TITLE: Fabric 0.0.3

Fabric is an oc-tool to build different project writen in different languages without having to remember all sort of commands and their required arguments.

Figure it out once, put it in a file and forget about it!

* Setting up a Fabric project

Simply open/create any project in any language.
Lets for this example assume you are writing a basic golang program/script.

Create a .fabric file (json format).

The current version only supports basic info, create any/all of the following fields ~build~, ~install~, ~clean~:

#+begin_src json
{
"build" : {},
"install": {},
"clean": {}
}
#+end_src

To actually specify what needs to be done in one of these fields/objects we need a ~command~ and optionally ~args~ to that command.

For our example we will only implement ~build~ and that might look like this:

#+begin_src json
{
    "build": {
        "command": "go",
        "args": [
            "build",
            "-ldflags",
            "-s -w"
        ]
    }
}
#+end_src
Now our Fabric project is all set up and ready to GO.

for a full example see this project's ~.fabric~ file.

* Building the Fabric project

building the fabric project is as simple as running ~fabric build~ in the project directory.

run ~fabric help~ for more commands

* Stuff thats left TODO

** Moving build output around

 A way to extract build sources may be useful to have similar outputs across projects, for example:
 - GO projects create a binary in the dir the command is ran ~./my-bin~
 - Python projects create ~./dist/my-project/my-bin~ asuming you use ~--one-file~ with pyinstaller
 - A C# project may create ~./bin/Debug/my-bin~ and/or ~./bin/Release/my-bin~

many other variations (probably) exist and you might want to configure fabric to copy file(s) from X to Y (and perhaps clean up afterwards?)

This is especially useful for automated pipelines with different languages.
You could have a generic function that calls ~fabric~  and moves the artifact(s) to ~./cicd-output/~ ready to be uploaded.

** Working with variables

With the addition of ~fabric install~ some build values are now duplicated and need to be updated on multiple places in the config file
Would be great to have a ~vars~ section and the posibility to use the vars in build/install/clean steps

** Auto clean

auto cleaning for special cases
